### ISSUE TITLE
Is ASP.NET Identity Core version available?

### ISSUE THREAD

**Issue by 1443403216** [xivSolutions/AspNetAdvancedRoleManagement#1]
Hi John,I tried to implement an ASP.NET Identity Core version by following ASP.NET MVC 5 Identity: Implementing Group-Based Permissions Management, but I was stuck with OnModelCreating due to the difference between ASP.NET Identity and ASP.NET Identity Core. Do you have a ASP.NET Identity Core version?Thanks! Leon

**Comment by xivSolutions** [comment]
Hello - 

I don't, and I think the concept here is actually pretty dated (although it served my needs at the time), and I would be looking at using a claims-based approach, if I were you. 

I may be trying to work up something for that, but there are also examples all over the web. 

Good luck!

**Comment by 1443403216** [comment]
Big thanks, John. Have a nice day!
